CREATE TABLE PERFIL_USUARIO (
                ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
                TIPO VARCHAR(20) NOT NULL,
                DESCRICAO VARCHAR(100) NOT NULL,
                SITUACAO INT NOT NULL
)

CREATE TABLE STATUS_USUARIO (
                ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
                DESCRICAO VARCHAR(50) NOT NULL
)

CREATE TABLE USUARIO (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_PERFIL_USUARIO INT NOT NULL,
                NOME VARCHAR(150) NOT NULL,
                EMAIL VARCHAR(150) NOT NULL,
                SENHA VARCHAR(20) NOT NULL,
                ID_STATUS_USUARIO INT NOT NULL,
                DT_CRIACAO DATETIME NOT NULL
)

CREATE TABLE LOCALIZACAO_PLANTAO (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                LOGRADOURO VARCHAR(200) NOT NULL,
                NUMERO INT NOT NULL,
                COMPLEMENTO VARCHAR(50) NULL,
                CIDADE VARCHAR(150) NOT NULL,
                ESTADO VARCHAR(100) NOT NULL,
                PAIS VARCHAR(50) NOT NULL,
                CEP VARCHAR(20) NOT NULL,
                GEOLOCALIZACAO VARCHAR(500) NOT NULL,
                ID_USUARIO_ALTERACAO UNIQUEIDENTIFIER NOT NULL,
                DT_ULTIMA_ALTERACAO DATETIME NOT NULL
)

CREATE TABLE PROJETO (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                NOME VARCHAR(100) NOT NULL,
                DESCRICAO VARCHAR(200) NOT NULL,
                ID_USUARIO_ALTERACAO UNIQUEIDENTIFIER NOT NULL,
                DT_ULTIMA_ALTERACAO DATETIME NOT NULL
)

CREATE TABLE PLANTAO (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_LOCALIZACAO_PLANTAO UNIQUEIDENTIFIER NOT NULL,
                ID_USUARIO_RESPONSAVEL UNIQUEIDENTIFIER NOT NULL,
                NOME_PLANTAO VARCHAR(150) NOT NULL,
                HORARIO_ABERTURA VARCHAR(5) NOT NULL,
                HORARIO_FECHAMENTO VARCHAR(5) NOT NULL,
                ID_USUARIO_ALTERACAO UNIQUEIDENTIFIER NOT NULL,
                DT_ULTIMA_ALTERACAO DATETIME NOT NULL
)

CREATE TABLE PROJETO_PLANTAO (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_PROJETO UNIQUEIDENTIFIER NOT NULL,
                ID_PLANTAO UNIQUEIDENTIFIER NOT NULL
)

CREATE TABLE OPERACAO (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_PLANTAO UNIQUEIDENTIFIER NOT NULL,
                DT_ABERTURA DATETIME NOT NULL,
                DT_FECHAMENTO DATETIME NOT NULL,
                HORARIO_BARRA VARCHAR(8) NOT NULL,
                HORARIO_POS_BARRA VARCHAR(8) NOT NULL,
                ID_USUARIO_ALTERACAO UNIQUEIDENTIFIER NOT NULL,
                DT_ULTIMA_ALTERACAO DATETIME NOT NULL
)

CREATE TABLE CODIGO_OPERACAO (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_OPERACAO UNIQUEIDENTIFIER NOT NULL,
                CODIGO VARCHAR(200) NOT NULL
)

CREATE TABLE OPERACAO_DIARIA (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_OPERACAO UNIQUEIDENTIFIER NOT NULL,
                DT_ABERTURA DATETIME NOT NULL
)

CREATE TABLE OPERACAO_DIARIA_CORRETOR (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_USUARIO UNIQUEIDENTIFIER NOT NULL,
                ID_OPERACAO_DIARIA UNIQUEIDENTIFIER NOT NULL,
                CHECKIN DATETIME NOT NULL,
                CHECKOUT DATETIME,
                ELEGIVEL_SORTEIO BIT NOT NULL,
                ELEGIVEL_ATENDIMENTO BIT NOT NULL,
                ID_USUARIO_ALTERACAO UNIQUEIDENTIFIER NOT NULL,
                DT_ALTERACAO DATETIME NOT NULL
)

CREATE TABLE STATUS_CORRETOR_ROLETA (
                ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
                DESCRICAO VARCHAR(20) NOT NULL
)

CREATE TABLE ROLETA (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_USUARIO UNIQUEIDENTIFIER NOT NULL,
                ID_OPERACAO_DIARIA UNIQUEIDENTIFIER NOT NULL,
                ID_STATUS_CORRETOR_ROLETA INT NOT NULL,
                ORDEM_INICIAL INT NOT NULL,
                ULTIMO_ATENDIMENTO BIT NOT NULL,
                POSICAO_ATUAL INT NOT NULL,
                DT_CRIACAO_ROLETA DATETIME NOT NULL,
                ID_USUARIO_ALTERACAO UNIQUEIDENTIFIER NOT NULL,
                DT_ALTERACAO DATETIME NOT NULL
)

CREATE TABLE CLIENTE (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                NOME VARCHAR(200) NOT NULL,
                CPF VARCHAR(11) NOT NULL,
                ID_USUARIO_ALTERACAO UNIQUEIDENTIFIER NOT NULL,
                DT_ULTIMA_ALTERACAO DATETIME NOT NULL
)

CREATE TABLE CLIENTE_CONTATO (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_CLIENTE UNIQUEIDENTIFIER NOT NULL,
                TELEFONE VARCHAR(13) NOT NULL,
                EMAIL VARCHAR(150) NOT NULL
)

CREATE TABLE ATENDIMENTO (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_OPERACAO_DIARIA_CORRETOR UNIQUEIDENTIFIER NOT NULL,
                ID_CLIENTE UNIQUEIDENTIFIER NOT NULL,
                DT_INICIO DATETIME NOT NULL,
                DT_TERMINO DATETIME,
                OBSERVACAO VARCHAR(300),
                ID_USUARIO_ALTERACAO UNIQUEIDENTIFIER NOT NULL,
                DT_ULTIMA_ALTERACAO DATETIME NOT NULL
)

CREATE TABLE AVALIACAO_ATENDIMENTO (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_ATENDIMENTO UNIQUEIDENTIFIER NOT NULL,
                ID_USUARIO_ADMIN UNIQUEIDENTIFIER,
                OBSERVACAO VARCHAR(300),
                AVALIACAO_POSITIVA BIT NOT NULL
)

CREATE TABLE OPERACAO_DIARIA_CORRETOR_LOG (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_OPERACAO UNIQUEIDENTIFIER NOT NULL,
                ID_USUARIO UNIQUEIDENTIFIER NOT NULL,
                CHECKIN DATETIME NOT NULL,
                CHECKOUT DATETIME NOT NULL,
                ELEGIVEL_SORTEIO BIT NOT NULL,
                ELEGIVEL_ATENDIMENTO BIT NOT NULL,
                ID_USUARIO_ALTERACAO UNIQUEIDENTIFIER NOT NULL,
                DT_ALTERACAO DATETIME NOT NULL
)

CREATE TABLE ROLETA_LOG (
                ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
                ID_USUARIO UNIQUEIDENTIFIER NOT NULL,
                ID_OPERACAO UNIQUEIDENTIFIER NOT NULL,
                ID_STATUS_CORRETOR INT NOT NULL,
                ORDEM_INICIAL INT NOT NULL,
                ULTIMO_ATENDIMENTO BIT NOT NULL,
                POSICAO_ATUAL INT NOT NULL,
                ID_USUARIO_ALTERACAO UNIQUEIDENTIFIER NOT NULL,
                DT_ALTERACAO DATETIME NOT NULL
)

ALTER TABLE USUARIO ADD CONSTRAINT STATUS_USUARIO_FK
FOREIGN KEY (ID_STATUS_USUARIO)
REFERENCES STATUS_USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE ROLETA ADD CONSTRAINT STATUS_CORRETOR_ROLETA_FK
FOREIGN KEY (ID_STATUS_CORRETOR_ROLETA)
REFERENCES STATUS_CORRETOR_ROLETA (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE USUARIO ADD CONSTRAINT PERFIL_USUARIO_FK
FOREIGN KEY (ID_PERFIL_USUARIO)
REFERENCES PERFIL_USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE PLANTAO ADD CONSTRAINT USUARIO_RESP_PLANTAO_FK
FOREIGN KEY (ID_USUARIO_RESPONSAVEL)
REFERENCES USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE OPERACAO_DIARIA_CORRETOR ADD CONSTRAINT USUARIO_OPDIARIA_FK
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE ROLETA ADD CONSTRAINT USUARIO_ROLETA_FK
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE CLIENTE ADD CONSTRAINT USUARIO_CLIENTE_FK
FOREIGN KEY (ID)
REFERENCES USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE OPERACAO_DIARIA_CORRETOR ADD CONSTRAINT USUARIO_OPDIARIA_INC_FK
FOREIGN KEY (ID_USUARIO_ALTERACAO)
REFERENCES USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE PLANTAO ADD CONSTRAINT USUARIO_ALT_PLANTAO_FK
FOREIGN KEY (ID_USUARIO_ALTERACAO)
REFERENCES USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE PROJETO ADD CONSTRAINT USUARIO_ALT_PROJETO_FK
FOREIGN KEY (ID_USUARIO_ALTERACAO)
REFERENCES USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE OPERACAO ADD CONSTRAINT USUARIO_ALT_OPERACAO_FK
FOREIGN KEY (ID_USUARIO_ALTERACAO)
REFERENCES USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE LOCALIZACAO_PLANTAO ADD CONSTRAINT USUARIO_ALT_LOCAL_PLANTAO_FK
FOREIGN KEY (ID_USUARIO_ALTERACAO)
REFERENCES USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE ATENDIMENTO ADD CONSTRAINT USUARIO_ALT_ATENDIMENTO_FK
FOREIGN KEY (ID_USUARIO_ALTERACAO)
REFERENCES USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE ROLETA ADD CONSTRAINT USUARIO_INC_ROLETA_FK
FOREIGN KEY (ID_USUARIO_ALTERACAO)
REFERENCES USUARIO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE CLIENTE_CONTATO ADD CONSTRAINT CLIENTE_CONTATO_FK
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE ATENDIMENTO ADD CONSTRAINT CLIENTE_ATEND_FK
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE PLANTAO ADD CONSTRAINT LOCALIZACAO_PLANTAO_FK
FOREIGN KEY (ID_LOCALIZACAO_PLANTAO)
REFERENCES LOCALIZACAO_PLANTAO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE PROJETO_PLANTAO ADD CONSTRAINT PLANTAO_PROJETO_FK
FOREIGN KEY (ID_PLANTAO)
REFERENCES PLANTAO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE OPERACAO ADD CONSTRAINT PLANTAO_OPERACAO_FK
FOREIGN KEY (ID_PLANTAO)
REFERENCES PLANTAO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE CODIGO_OPERACAO ADD CONSTRAINT OPERACAO_CODIGO_FK
FOREIGN KEY (ID_OPERACAO)
REFERENCES OPERACAO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE OPERACAO_DIARIA ADD CONSTRAINT OPERACAO_DIARIA_FK
FOREIGN KEY (ID_OPERACAO)
REFERENCES OPERACAO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE OPERACAO_DIARIA_CORRETOR ADD CONSTRAINT OPERACAO_DIARIA_CORRETOR_FK
FOREIGN KEY (ID_OPERACAO_DIARIA)
REFERENCES OPERACAO_DIARIA (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE ROLETA ADD CONSTRAINT OPERACAO_DIARIA_ROLETA_FK
FOREIGN KEY (ID_OPERACAO_DIARIA)
REFERENCES OPERACAO_DIARIA (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE ATENDIMENTO ADD CONSTRAINT OPDIARIA_ATEND_FK
FOREIGN KEY (ID_OPERACAO_DIARIA_CORRETOR)
REFERENCES OPERACAO_DIARIA_CORRETOR (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE AVALIACAO_ATENDIMENTO ADD CONSTRAINT ATENDIMENTO_AVALIACAO_FK
FOREIGN KEY (ID_ATENDIMENTO)
REFERENCES ATENDIMENTO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE PROJETO_PLANTAO ADD CONSTRAINT PROJETO_PLANTAO_FK
FOREIGN KEY (ID_PROJETO)
REFERENCES PROJETO (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION